import { useMemo, useState } from 'react';
import { Badge, Button, Field, Input, Modal, PageHeader, Table } from '../components/UI.jsx';
import { useApp } from '../context/AppContext.jsx';

function money(value){ return `Rs ${Number(value || 0).toLocaleString('en-MU', { minimumFractionDigits:2, maximumFractionDigits:2 })}`; }
function cleanPart(p){ return { ...p, name:p.name || p.part || '', sellingPrice:Number(p.sellingPrice ?? p.lastPrice ?? p.price ?? 0), stock:Number(p.stock ?? p.currentStock ?? 0), supplier:p.supplier || p.supplierName || '' }; }

export default function Inventory(){
  const { inventory=[], createPO, createInventoryItem, updateInventoryItem, addInventoryStock } = useApp();
  const [search,setSearch]=useState('');
  const [modal,setModal]=useState(null);
  const items=useMemo(()=>inventory.map(cleanPart).filter(p=>JSON.stringify(p).toLowerCase().includes(search.toLowerCase())),[inventory,search]);
  return <div className="page">
    <PageHeader title="Store Keeper / Parts" subtitle="Editable DB parts: SKU, Part, Selling Price, Stock, Reorder Level and Supplier. Stock issued to assessments/garage work is deducted from the database." action={()=>setModal({type:'add'})} actionLabel="Add Part" />
    <div className="history-toolbar"><Input placeholder="Search SKU, part, supplier..." value={search} onChange={e=>setSearch(e.target.value)} /><Button variant="secondary" onClick={()=>setModal({type:'stock'})}>Input New Stock</Button></div>
    <Table headers={["SKU","Part","Selling Price","Stock","Reorder Level","Supplier","Status","Actions"]}>
      {items.map(p=>{ const low=p.stock<=Number(p.reorderLevel||0); return <tr key={p.id || p.sku}>
        <td><b>{p.sku}</b></td><td>{p.name}</td><td><b>{money(p.sellingPrice)}</b></td><td>{p.stock}</td><td>{p.reorderLevel}</td><td>{p.supplier || '-'}</td>
        <td><Badge tone={low?'danger':'success'}>{low?'Re-order':'OK'}</Badge></td>
        <td className="row-actions"><button className="open-btn" onClick={()=>setModal({type:'edit',item:p})}>Edit</button><button className="open-btn" onClick={()=>setModal({type:'addStock',item:p})}>Add Stock</button><button className="open-btn" onClick={()=>setModal({type:'po',item:p})}>PO</button></td>
      </tr>})}
    </Table>
    {modal?.type==='add' && <Modal title="Add New Part" onClose={()=>setModal(null)} wide><PartForm onSave={async f=>{await createInventoryItem(f); setModal(null);}} /></Modal>}
    {modal?.type==='edit' && <Modal title="Edit Part" onClose={()=>setModal(null)} wide><PartForm initial={modal.item} onSave={async f=>{await updateInventoryItem(modal.item.dbId || modal.item.id, f); setModal(null);}} /></Modal>}
    {modal?.type==='addStock' && <Modal title="Input New Stock" onClose={()=>setModal(null)}><StockForm part={modal.item} onSave={async (qty,reason)=>{await addInventoryStock(modal.item.dbId || modal.item.id, qty, reason); setModal(null);}} /></Modal>}
    {modal?.type==='stock' && <Modal title="Input New Stock" onClose={()=>setModal(null)}><StockPicker parts={items} onSave={async (part,qty,reason)=>{await addInventoryStock(part.dbId || part.id, qty, reason); setModal(null);}} /></Modal>}
    {modal?.type==='po' && <Modal title="Purchase Order Form" onClose={()=>setModal(null)} wide><POForm part={modal.item} createPO={createPO} /></Modal>}
  </div>
}

function PartForm({initial={},onSave}){ const [f,setF]=useState({ sku:initial.sku||'', name:initial.name||'', sellingPrice:initial.sellingPrice ?? initial.lastPrice ?? '', stock:initial.stock ?? '', reorderLevel:initial.reorderLevel ?? '', supplier:initial.supplier||'', supplierEmail:initial.supplierEmail||'', category:initial.category||'', location:initial.location||'' }); return <form onSubmit={e=>{e.preventDefault(); onSave(f);}}><div className="form-grid"><Field label="SKU"><Input required value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/></Field><Field label="Part"><Input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Selling Price"><Input type="number" step="0.01" value={f.sellingPrice} onChange={e=>setF({...f,sellingPrice:e.target.value})}/></Field><Field label="Stock"><Input type="number" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/></Field><Field label="Reorder Level"><Input type="number" value={f.reorderLevel} onChange={e=>setF({...f,reorderLevel:e.target.value})}/></Field><Field label="Supplier"><Input value={f.supplier} onChange={e=>setF({...f,supplier:e.target.value})}/></Field><Field label="Supplier Email"><Input value={f.supplierEmail} onChange={e=>setF({...f,supplierEmail:e.target.value})}/></Field><Field label="Location"><Input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></Field></div><Button>Save to Database</Button></form> }
function StockForm({part,onSave}){ const [qty,setQty]=useState(''); const [reason,setReason]=useState('New stock input'); return <form onSubmit={e=>{e.preventDefault(); onSave(qty,reason);}}><p><b>{part.sku}</b> - {part.name}</p><Field label="Quantity to add"><Input type="number" required value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Reason"><Input value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button>Update DB Stock</Button></form> }
function StockPicker({parts,onSave}){ const [id,setId]=useState(parts[0]?.id || ''); const [qty,setQty]=useState(''); const [reason,setReason]=useState('New stock input'); const part=parts.find(p=>p.id===id); return <form onSubmit={e=>{e.preventDefault(); if(part) onSave(part,qty,reason);}}><Field label="Part"><select className="input" value={id} onChange={e=>setId(e.target.value)}>{parts.map(p=><option key={p.id} value={p.id}>{p.sku} - {p.name}</option>)}</select></Field><Field label="Quantity to add"><Input type="number" required value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Reason"><Input value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button>Update DB Stock</Button></form> }
function POForm({part,createPO}){ const price=Number(part.sellingPrice||0); const [qty,setQty]=useState(10); const [msg,setMsg]=useState(`Dear Supplier,\n\nPlease process this purchase order for ${part.name}.`); async function save(){ await createPO(part, qty, { quantity:qty, item:part.name, supplier:part.supplier, supplierEmail:part.supplierEmail, amount:price*qty, message:msg }); } return <div><p><b>{part.sku}</b> - {part.name}</p><Field label="Quantity"><Input type="number" value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Amount"><Input readOnly value={money(price*Number(qty||0))}/></Field><Field label="Message"><textarea className="input textarea" value={msg} onChange={e=>setMsg(e.target.value)}/></Field><Button onClick={save}>Create PO Transaction</Button></div> }
